# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest      
    steps:
      - checkout
      - run: npm i
      - run: npm run build